config/routes.rb
Rails.application.routes.draw do
    root "ideas#index"
    get "ideas/reload" => "ideas#index"
    post "/questions/:id/toggle" => "questions#toggle"
    get "/questions/restart" => "questions#restart"
  # get 'questions/index'
  resources :ideas
  resources :questions

  # get 'ideas/index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    validates :item,
    presence: { message: '入力がありません'},
    length: { maximum: 100, message: '100文字以内で書いて下さい'}
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
    @questions = Question.all
  end
  def new
  @idea = Idea.new
  @questions = Question.all
  end
  def create
      @questions = Question.all
  @idea = Idea.new(idea_params)
  if @idea.save
    redirect_to root_path
  else
    render "new"
  end
  end
  
  def reload
    @ideas = Idea.all
  end
  
  private
  def idea_params
  params[:idea].permit(:item)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @question = Question.new
    @questions = Question.all
  end
  def create
  @question = Question.new(question_params)
  if @question.save
    redirect_to questions_path
  else
    render "new"
  end
  end
    def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
    end
    
    def toggle
    head :no_content
    # 一度全てfalseにしてから、選択されたものだけ論理反転
    # @questions = Question.all
    # @questions.ask = false
    # @questions.save
    # 上記ではダメ、下記にしたらOKになった。
    Question.update_all(ask: false)
    
    @question = Question.find(params[:id])
    @question.ask = !@question.ask
    @question.save
    end
    
    def restart
    Idea.delete_all
    redirect_to root_path
    end
  
  private
  def question_params
  params[:question].permit(:item)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/ideas/index.html.erb
        <div class="questionline">
    <% @questions.each do |question| %>
    <% if question.ask == true then %>
    <%= question.item %>
    <% end %>
    <% end %>
</div>

<ul class = "all_ideas">
    <% @ideas.each do |idea| %>
    <li class = "individual_idea">
    <%= idea.item %>
    </li>
    <% end %>

   <li id="your_idea" class="individual_idea">    
    <%= link_to new_idea_path do %>

       回答を書く

    <% end %>
               </li>
    
</ul>

<script>
if (typeof timerstart === "undefined"){
let timerstart = 0;
}
console.log("page reloaded!");
function startTimer() {
  timerstart = setInterval("location.reload()", 3000);
  console.log("started!");
}
function timerstop() {
  console.log("stopping");
  clearInterval(timerstart);
}
function timerrestart() {
  console.log("restart");
  timerstart = setInterval("location.reload()", 3000);
  console.log("timer id is " + timerstart);
}
startTimer();
document
  .getElementById("your_idea")
  .addEventListener("mouseenter", timerstop);
document
  .getElementById("your_idea")
  .addEventListener("mouseleave", timerrestart);

document
  .getElementById("visibility")
  .addEventListener("mouseenter", timerstop);
document
  .getElementById("visibility")
  .addEventListener("mouseleave", timerrestart);

document
  .getElementById("edit")
  .addEventListener("mouseenter", timerstop);
document
  .getElementById("edit")
  .addEventListener("mouseleave", timerrestart);

document
  .getElementById("manage_accounts")
  .addEventListener("mouseenter", timerstop);
document
  .getElementById("manage_accounts")
  .addEventListener("mouseleave", timerrestart);
</script>

app/views/ideas/new.html.erb
        <div class="questionline">
    <% @questions.each do |question| %>
    <% if question.ask == true then %>
    <%= question.item %>
    <% end %>
    <% end %>
</div>

<%= form_for @idea do |youridea| %>
<div class = "writeyouridea">
<p>    <!--<%= youridea.label :回答を書く %>-->
    <%= youridea.text_area :item, placeholder:"回答を書く(100文字以内)", size:"50x4", maxlength:"100" %>
    <% if @idea.errors.any? %>
    <%= @idea.errors.messages[:item][0] %>
        <% end %></p>
        <p>
        <%= youridea.submit "回答する" %>
</p>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sparkthink 50 あなたの考えを共有しましょう</title>
    <%= csrf_meta_tags %>
    <meta property="og:title" content＝"Sparkthink 50 あなたの考えを共有しましょう" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Oleo+Script&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
      rel="stylesheet">
 
  </head>

  <body>
    <header>
      <div class="header_titles">
      <span class="header_title">Sparkthink 50</span>
      <span class="header_subtitle">Share your ideas</span>
      </div>
      <nav>
        <ul>
          <li>
            <%= link_to root_path do %>
            <span id="visibility" class="material-icons-outlined">
            visibility
            </span>
            <% end %>

          </li>
          <li>
            <%= link_to new_idea_path do %>
            <span id="edit" class="material-icons-outlined">
            edit
            </span>
                        <% end %>
          </li>
          <li>
               <%= link_to questions_path do %>
            <span id="manage_accounts" class="material-icons-outlined">
            manage_accounts
            </span>
                        <% end %>
          </li>
        </ul>
      </nav>

    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <span class="footer_text">
        Developed by Morihiro
      </span>
    </footer>
  </body>
</html>

app/views/questions/index.html.erb
<div class="questionbox">
<%= form_for @question do |yourquestion| %>
    <%= yourquestion.label :質問候補を書く %><br>
    <%= yourquestion.text_field :item %><br>
    <%= yourquestion.submit %>
    <%end%>
</div>


<div class="questionbox">
<p>以下の質問候補から質問を選択して、ボタンを押して下さい<br><%= link_to(questions_restart_path) do %>
<button>Ask Question</button>
<% end %>
</p>


    <% @questions.reverse_each do |question| %>
    <div>
    <%= radio_button_tag name= "radio" '','', question.ask, {"data-id" => question.id } %>
    <%= question.item %>
    <%= link_to "削除", question_path(question.id),
                        method: :delete,
                        data:{ confirm: "削除してもよろしいですか？"} %>
    </div>
    <% end %>
    </div>







<script>
       $(function() {
        $("input[type=radio]").click(function(){
            $.post("/questions/" + $(this).data("id") + "/toggle");
        });
    }); 
    
</script>

<!--INPUTとJSの両方をRadioにする-->